include:
  - path: ./backend/docker-compose.dev.yml
  - path: ./frontend/docker-compose.dev.yml

services:
  postgres:
    image: postgres:16-alpine
    container_name: acta_postgres_dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - acta_network_dev
    restart: unless-stopped


volumes:
  postgres_data_dev:
    driver: local

networks:
  acta_network_dev:
    driver: bridge
